# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6822763fb754a572bacd47fa3c9e2bd57a3e5fbc241f5204152943de999ff77374c24bb1ecffdda58fcbbdb8a3d5309365a7797a8a31dd7e8e5e49e08c1675d

test:
  secret_key_base: bb53a1ff78dc03099234b670591dcf6f5a72b7267b12e3e86cde67324cf2913654eccb878a22f79da758f297bdbf4a0cda06c250d5e2be696a4aae0178d83bda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
